[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "no-std"]
description = "A template for building applications for ARM Cortex-M microcontrollers"
keywords = ["arm", "cortex-m", "template"]
license = "MIT OR Apache-2.0"
name = "cortex-m-quickstart"
repository = "https://github.com/japaric/cortex-m-quickstart"
version = "0.2.7"

[dependencies]
# cortex-m = "0.4.0"
# cortex-m-rt = "0.4.0"
cortex-m-rt = { git = "https://github.com/japaric/cortex-m-rt", branch = "stable" }
# cortex-m-semihosting = "0.2.0"
# panic-loop = { path = "../panic-loop" }
panic-abort = "0.1.1"
# panic-semihosting = "0.1.0"
# Uncomment for the allocator example.
#alloc-cortex-m = "0.3.3"

# Uncomment for the device example.
# [dependencies.stm32f103xx]
# features = ["rt"]
# version = "0.9.0"

[profile.release]
debug = true
lto = true
opt-level = "s"
